amz_profile_school:
    resource: "@AMZProfileBundle/Resources/config/route/school.yml"
    prefix:   /profile/school

amz_profile_routes:
    resource: "@AMZProfileBundle/Resources/config/route/profile.yml"
    prefix:   /profile

amz_profile_class_unit:
    resource: "@AMZProfileBundle/Resources/config/route/class-unit.yml"
    prefix:   /profile/class/unit

amz_profile_school_year:
    resource: "@AMZProfileBundle/Resources/config/route/school-year.yml"
    prefix:   /profile/school/year

amz_bmi_result:
    resource: "@AMZProfileBundle/Resources/config/route/bmi-result.yml"
    prefix:   /bmi/result