<?php

namespace AMZ\SliderBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    private function init($criteria)
    {
        $qb = $this->createQueryBuilder('t');
        if (!empty($criteria['admin_keyword'])) {
            $qb->andWhere(
                $qb->expr()->orX(
                    $qb->expr()->like('t.title1', $qb->expr()->literal("%{$criteria['admin_keyword']}%"))
                )
            );
        }
        if (isset($criteria['id'])) {
            $qb->andWhere(
                $qb->expr()->eq('t.id', $criteria['id'])
            );
        }
        if (!empty($criteria['position'])) {
            $qb->andWhere(
                $qb->expr()->eq('t.position', $criteria['position'])
            );
        }
        if (!empty($criteria['position-slug'])) {
            $qb->leftJoin('t.position', 'p');
            $qb->andWhere(
                $qb->expr()->like('p.slug', $qb->expr()->literal($criteria['position-slug']))
            );
        }
        return $qb;
    }

    private function order(array $orderBy = null, QueryBuilder &$qb)
    {
        if (!empty($orderBy['sort-order'])) {
            $qb->addOrderBy('t.sortOrder', $orderBy['sort-order']);
        }
        if (!empty($orderBy['id'])) {
            $qb->addOrderBy('t.id', $orderBy['id']);
        }
        if (empty($orderBy)) {
            $qb->orderBy('t.sortOrder', 'ASC');
        }
    }

    public function findOneBy(array $criteria, array $orderBy = null)
    {
        $qb = $this->init($criteria);
        $qb->setFirstResult(0)
            ->setMaxResults(1);
        $this->order($orderBy, $qb);
        $qb->groupBy('t.id');
        return $qb->getQuery()->getSingleResult();
    }

    public function get($criteria, array $orderBy = null)
    {
        $qb = $this->init($criteria);
        $this->order($orderBy, $qb);
        $qb->groupBy('t.id');
        return $qb->getQuery()->getResult();
    }

    public function query($criteria)
    {
        $qb = $this->init($criteria);
        $qb->groupBy('t.id');
        return $qb->getDQL();
    }
}
