amz_doctor_user_index:
    path:      /
    defaults:  { _controller: AMZUserBundle:DoctorUser:index }
    methods: [GET]

amz_doctor_user_create:
    path:      /create
    defaults:  { _controller: AMZUserBundle:DoctorUser:create }

amz_doctor_user_edit:
    path:      /{id}/edit
    defaults:  { _controller: AMZUserBundle:DoctorUser:edit }

amz_doctor_user_delete:
    path:      /{id}/delete
    defaults:  { _controller: AMZUserBundle:DoctorUser:delete }