amz_school_user_index:
    path:      /
    defaults:  { _controller: AMZUserBundle:SchoolUser:index }
    methods: [GET]

amz_school_user_create:
    path:      /create
    defaults:  { _controller: AMZUserBundle:SchoolUser:create }

amz_school_user_edit:
    path:      /{id}/edit
    defaults:  { _controller: AMZUserBundle:SchoolUser:edit }

amz_school_user_delete:
    path:      /{id}/delete
    defaults:  { _controller: AMZUserBundle:SchoolUser:delete }