<?php

namespace AMZ\BackendBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * OptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{

}
