application_business_index:
    path:     /
    defaults: { _controller: AppBundle:Business:index }

application_business_page:
    path:     /{slug}
    defaults: { _controller: AppBundle:Business:page }
