application_statistic_index:
    path:     /
    defaults: { _controller: AppBundle:Statistics:reportByClass }

application_statistic_by_school:
    path:     /theo-truong-hoc
    defaults: { _controller: AppBundle:Statistics:reportBySchool }

application_statistic_by_schoolUnit:
    path:     /theo-khoi-lop
    defaults: { _controller: AppBundle:Statistics:reportBySchoolUnit }

application_statistic_by_district:
    path:     /theo-quan-huyen
    defaults: { _controller: AppBundle:Statistics:reportByDistrict }

application_statistic_by_city:
    path:     /theo-tinh-thanh
    defaults: { _controller: AppBundle:Statistics:reportByCity }

application_statistic_by_all:
    path:     /toan-quoc
    defaults: { _controller: AppBundle:Statistics:reportByAll }

application_statistic_export:
    path:     /xuat
    defaults: { _controller: AppBundle:Statistics:exportForClass }

application_statistic_export_school:
    path:     /xuat-theo-truong
    defaults: { _controller: AppBundle:Statistics:exportForSchool }

application_statistic_export_school_unit:
    path:     /xuat-theo-khoi-lop
    defaults: { _controller: AppBundle:Statistics:exportForSchoolUnit }

application_statistic_export_district:
    path:     /xuat-theo-quan-huyen
    defaults: { _controller: AppBundle:Statistics:exportForDistrict }

application_statistic_export_city:
    path:     /xuat-theo-tinh-thanh
    defaults: { _controller: AppBundle:Statistics:exportForCity }

application_statistic_export_all:
    path:     /xuat-toan-quoc
    defaults: { _controller: AppBundle:Statistics:exportForAll }


application_statistic_change_city:
    path:     /ajax/change-city
    defaults: { _controller: AppBundle:Statistics:ajaxChangeCity }

application_statistic_change_district:
    path:     /ajax/change-district
    defaults: { _controller: AppBundle:Statistics:ajaxChangeDistrict }

application_statistic_change_year:
    path:     /ajax/change-year
    defaults: { _controller: AppBundle:Statistics:ajaxChangeYear }