<?php

namespace AMZ\ProfileBundle\Repository;

/**
 * ProfileClassesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileClassesRepository extends \Doctrine\ORM\EntityRepository
{
}
