application_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

application_security_test_login:
    path:     /dang-nhap
    defaults: { _controller: AppBundle:Security:login }

application_logout:
    path:      /dang-xuat

application_login_check:
    path:      /check-login


application_security:
    resource: "@AppBundle/Resources/config/route/security.yml"
    prefix:   /security
application_page:
    resource: "@AppBundle/Resources/config/route/page.yml"
    prefix:   /thong-tin

application_post:
    resource: "@AppBundle/Resources/config/route/post.yml"
    prefix:   /bai-viet

application_education:
    resource: "@AppBundle/Resources/config/route/education.yml"
    prefix:   /dao-tao