application_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

application_security_test_login:
    path:     /dang-nhap
    defaults: { _controller: AppBundle:Security:login }

application_logout:
    path:      /dang-xuat

application_login_check:
    path:      /check-login


application_security:
    resource: "@AppBundle/Resources/config/route/security.yml"
    prefix:   /security
application_page:
    resource: "@AppBundle/Resources/config/route/page.yml"
    prefix:   /thong-tin

application_post:
    resource: "@AppBundle/Resources/config/route/post.yml"
    prefix:   /bai-viet

application_education:
    resource: "@AppBundle/Resources/config/route/education.yml"
    prefix:   /dao-tao

application_event:
    resource: "@AppBundle/Resources/config/route/event.yml"
    prefix:   /su-kien

application_admission:
    resource: "@AppBundle/Resources/config/route/admission.yml"
    prefix:   /tuyen-sinh

application_research:
    resource: "@AppBundle/Resources/config/route/research.yml"
    prefix:   /nghien-cuu

application_business:
    resource: "@AppBundle/Resources/config/route/business.yml"
    prefix:   /hop-tac-doanh-nghiep

application_news:
    resource: "@AppBundle/Resources/config/route/news.yml"
    prefix:   /tin-tuc

application_page_csdt:
    path:     /co-so-dao-tao
    defaults: { _controller: AppBundle:Page:location }

application_page_intro:
    path:     /gioi-thieu
    defaults: { _controller: AppBundle:Intro:index }

application_search:
    path:     /tim-kiem
    defaults: { _controller: AppBundle:Search:index }