<?php

namespace AMZ\PostBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    private function init($criteria)
    {
        $qb = $this->createQueryBuilder('t');
        if (!empty($criteria['admin_keyword'])) {
            $qb->andWhere(
                $qb->expr()->orX(
                    $qb->expr()->like('t.title', $qb->expr()->literal("%{$criteria['admin_keyword']}%"))
                )
            );
        }
        if (isset($criteria['id'])) {
            $qb->andWhere(
                $qb->expr()->eq('t.id', $criteria['id'])
            );
        }
        if (!empty($criteria['slug'])) {
            $qb->andWhere(
                $qb->expr()->like('t.slug', $qb->expr()->literal($criteria['slug']))
            );
        }
        if (isset($criteria['is_featured'])) {
            $qb->andWhere(
                $qb->expr()->eq('t.is_featured', $criteria['is_featured'])
            );
        }
        if (isset($criteria['level'])) {
            $qb->andWhere(
                $qb->expr()->eq('t.level', $criteria['level'])
            );
        }
        if (isset($criteria['parent'])) {
            $qb->andWhere(
                $qb->expr()->eq('t.parent', $criteria['parent'])
            );
        }
        if (isset($criteria['parent_slug'])) {
            $qb->leftJoin('t.categories', 'c');
            $qb->andWhere(
                $qb->expr()->like('c.slug', $qb->expr()->literal($criteria['parent_slug']))
            );
        }
        return $qb;
    }

    private function order(array $orderBy = null, QueryBuilder &$qb)
    {
        if (!empty($orderBy['sort_order'])) {
            $qb->addOrderBy(
                't.sortOrder',
                $orderBy['sort_order']
            );
        }
    }

    public function findOneBy(array $criteria, array $orderBy = null)
    {
        $qb = $this->init($criteria);
        $qb->setFirstResult(0)
            ->setMaxResults(1);
        $this->order($orderBy, $qb);
        $qb->groupBy('t.id');
        return $qb->getQuery()->getSingleResult();
    }

    public function get(array $criteria = null, array $orderBy = null)
    {
        $qb = $this->init($criteria);
        $this->order($orderBy, $qb);
        $qb->groupBy('t.id');
        return $qb->getQuery()->getResult();
    }

    public function query($criteria)
    {
        $qb = $this->init($criteria);
        $qb->groupBy('t.id');
        return $qb->getDQL();
    }
}
