<?php

namespace AMZ\PostBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends \Doctrine\ORM\EntityRepository
{
    private function init($criteria)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->leftJoin('t.post', 'p');
        if (!empty($criteria['admin_keyword'])) {
            $qb->andWhere(
                $qb->expr()->orX(
                    $qb->expr()->like('t.title1', $qb->expr()->literal("%{$criteria['admin_keyword']}%"))
                )
            );
        }
        if (isset($criteria['id'])) {
            $qb->andWhere(
                $qb->expr()->eq('t.id', $criteria['id'])
            );
        }
        if (isset($criteria['post'])) {
            $qb->andWhere(
                $qb->expr()->eq('p.id', $criteria['post'])
            );
        }
        if (isset($criteria['post_id'])) {
            $qb->andWhere(
                $qb->expr()->eq('p.id', $criteria['post_id'])
            );
        }
        return $qb;
    }

    private function order(array $orderBy = null, QueryBuilder &$qb)
    {

    }

    public function findOneBy(array $criteria, array $orderBy = null)
    {
        $qb = $this->init($criteria);
        $qb->setFirstResult(0)
            ->setMaxResults(1);
        $this->order($orderBy, $qb);
        $qb->groupBy('t.id');
        return $qb->getQuery()->getSingleResult();
    }

    public function get($criteria)
    {
        $qb = $this->init($criteria);
        $qb->groupBy('t.id');
        return $qb->getQuery()->getResult();
    }

    public function query($criteria)
    {
        $qb = $this->init($criteria);
        $qb->groupBy('t.id');
        return $qb->getDQL();
    }
}
