amz_post_homepage:
    path:     /
    defaults: { _controller: AMZPostBundle:Post:index }

amz_post_create:
    path:     /create
    defaults: { _controller: AMZPostBundle:Post:create }

amz_post_edit:
    path:     /{id}/edit
    defaults: { _controller: AMZPostBundle:Post:edit }

amz_post_delete:
    path:     /{id}/delete
    defaults: { _controller: AMZPostBundle:Post:delete }

amz_post_gallery:
    resource: "@AMZPostBundle/Resources/config/route/post-gallery.yml"
    prefix:     /{post_id}/gallery

amz_post_list_by_cat:
    path:     /cat/{catID}
    defaults: { _controller: AMZPostBundle:Post:getByCategory }

amz_post_create_by_cat:
        path:     /create/{catID}
        defaults: { _controller: AMZPostBundle:Post:createByCategory }