amz_post_gallery_homepage:
    path:     /
    defaults: { _controller: AMZPostBundle:PostGallery:index }

amz_post_gallery_create:
    path:     /create
    defaults: { _controller: AMZPostBundle:PostGallery:create }

amz_post_gallery_edit:
    path:     /{id}/edit
    defaults: { _controller: AMZPostBundle:PostGallery:edit }

amz_post_gallery_delete:
    path:     /{id}/delete
    defaults: { _controller: AMZPostBundle:PostGallery:delete }