amz_post_tag_homepage:
    path:     /
    defaults: { _controller: AMZPostBundle:Tag:index }

amz_post_tag_create:
    path:     /create
    defaults: { _controller: AMZPostBundle:Tag:create }

amz_post_tag_edit:
    path:     /{id}/edit
    defaults: { _controller: AMZPostBundle:Tag:edit }

amz_post_tag_delete:
    path:     /{id}/delete
    defaults: { _controller: AMZPostBundle:Tag:delete }