amz_profile_homepage:
    path:     /
    defaults: { _controller: AMZProfileBundle:Profile:index }

amz_profile_create:
    path:     /create
    defaults: { _controller: AMZProfileBundle:Profile:create }

amz_profile_edit:
    path:     /{id}/edit
    defaults: { _controller: AMZProfileBundle:Profile:edit }

amz_profile_delete:
    path:     /{id}/delete
    defaults: { _controller: AMZProfileBundle:Profile:delete }