amz_profile_school_homepage:
    path:     /
    defaults: { _controller: AMZProfileBundle:School:index }

amz_profile_school_create:
    path:     /create
    defaults: { _controller: AMZProfileBundle:School:create }

amz_profile_school_edit:
    path:     /{id}/edit
    defaults: { _controller: AMZProfileBundle:School:edit }

amz_profile_school_delete:
    path:     /{id}/delete
    defaults: { _controller: AMZProfileBundle:School:delete }

amz_profile_class:
    resource: "@AMZProfileBundle/Resources/config/route/class.yml"
    prefix:   /{school}/class